<?php

declare(strict_types=1);

namespace TalesFromADev\TailwindMerge\Support;

use TalesFromADev\TailwindMerge\Validators\ValidatorInterface;
use TalesFromADev\TailwindMerge\ValueObjects\ClassPartObject;

/**
 * Flattens the class map trie into two lookup tables, so the default one can
 * ship as constants opcache keeps in shared memory (see DefaultClassMap):
 *
 * - literals: class path => class group id, for every trie node with a group.
 *   An exact path wins over any validator in the trie walk, so a hit here is
 *   the walk's answer.
 * - validators: path of a node with validators, dash-terminated so the root
 *   ('') cannot collide with a child named '', => its validators in order.
 *
 * @internal
 *
 * @phpstan-type Validator class-string<ValidatorInterface>|\Closure
 * @phpstan-type CompiledClassMap array{
 *       literals: array<string, string>,
 *       validators: array<string, list<array{Validator, string}>>,
 *   }
 */
final class ClassMapCompiler
{
    /**
     * @param array<string, list<mixed>> $classGroups
     * @param array<string, list<mixed>> $theme
     *
     * @return CompiledClassMap
     */
    public static function compile(array $classGroups, array $theme): array
    {
        $compiledClassMap = ['literals' => [], 'validators' => []];

        $root = (new ClassMap())->processClassGroup($classGroups, $theme);

        // The root group is unreachable: a class always has at least one part.
        self::collectValidators($root, '', $compiledClassMap);

        foreach ($root->nextPart as $part => $child) {
            self::collect($child, (string) $part, $compiledClassMap);
        }

        return $compiledClassMap;
    }

    /**
     * Renders a compiled class map as the source of DefaultClassMap.
     *
     * @param CompiledClassMap $compiledClassMap
     */
    public static function toSource(array $compiledClassMap): string
    {
        $validatorClasses = [];
        $literals = '';
        $validators = '';

        foreach ($compiledClassMap['literals'] as $path => $classGroupId) {
            $literals .= \sprintf("        %s => %s,\n", var_export($path, true), var_export($classGroupId, true));
        }

        foreach ($compiledClassMap['validators'] as $path => $entries) {
            $validators .= \sprintf("        %s => [\n", var_export($path, true));

            foreach ($entries as [$validator, $classGroupId]) {
                if (!\is_string($validator)) {
                    throw new \LogicException(\sprintf('The validator of class group "%s" is a closure, which cannot be compiled to source.', $classGroupId));
                }

                $validatorClasses[$validator] = true;
                $validators .= \sprintf("            [%s::class, %s],\n", self::shortName($validator), var_export($classGroupId, true));
            }

            $validators .= "        ],\n";
        }

        ksort($validatorClasses);
        $uses = '';
        foreach (array_keys($validatorClasses) as $validatorClass) {
            $uses .= "use {$validatorClass};\n";
        }

        return <<<PHP
            <?php

            declare(strict_types=1);

            namespace TalesFromADev\\TailwindMerge\\Support;

            {$uses}
            /**
             * GENERATED by `composer compile:class-map` from Config::getDefaultConfig(). Do not edit.
             *
             * @internal
             */
            final class DefaultClassMap
            {
                public const LITERALS = [
            {$literals}    ];

                public const VALIDATORS = [
            {$validators}    ];
            }

            PHP;
    }

    /**
     * @param CompiledClassMap $compiledClassMap
     */
    private static function collect(ClassPartObject $node, string $path, array &$compiledClassMap): void
    {
        if (null !== $node->classGroupId) {
            $compiledClassMap['literals'][$path] = $node->classGroupId;
        }

        self::collectValidators($node, $path.ClassMap::CLASS_PART_SEPARATOR, $compiledClassMap);

        foreach ($node->nextPart as $part => $child) {
            self::collect($child, $path.ClassMap::CLASS_PART_SEPARATOR.$part, $compiledClassMap);
        }
    }

    /**
     * @param CompiledClassMap $compiledClassMap
     */
    private static function collectValidators(ClassPartObject $node, string $key, array &$compiledClassMap): void
    {
        foreach ($node->validators as $validator) {
            $compiledClassMap['validators'][$key][] = [self::describeValidator($validator->validator), $validator->classGroupId];
        }
    }

    /**
     * @return class-string<ValidatorInterface>|\Closure
     */
    private static function describeValidator(\Closure $validator): string|\Closure
    {
        // `FooValidator::validate(...)` becomes its class name, so it can be written to source.
        $reflection = new \ReflectionFunction($validator);
        $scopeClass = $reflection->getClosureScopeClass()?->getName();

        if ('validate' === $reflection->getName()
            && $reflection->isStatic()
            && null !== $scopeClass
            && is_a($scopeClass, ValidatorInterface::class, true)
        ) {
            return $scopeClass;
        }

        return $validator;
    }

    private static function shortName(string $class): string
    {
        $position = strrpos($class, '\\');

        return false === $position ? $class : substr($class, $position + 1);
    }
}
